name: "Close DIFF_VIEWER_REPO PRs on PR close"

on:
  pull_request:
    types:
      - closed

jobs:
  close-diff-viewer-pr:
    name: Close diff viewer PR
    runs-on: ubuntu-slim
    timeout-minutes: 3
    steps:
      - uses: Himenon/diff-artifact/close-pr@v1.1.0
        with:
          app-id: ${{ secrets.APP_ID }}
          app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
          diff-viewer-owner: Himenon
          diff-viewer-repo-name: diff-artifacts-example-diff-viewer
