name: "Close DIFF_VIEWER_REPO PRs on PR close"

on:
  pull_request:
    types:
      - closed

jobs:
  close-diff-viewer-pr:
    name: Close diff viewer PR
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: Himenon/close-diff-artifact-pr@a2dbed3129e26306becce793019c1d77647fe0be
        with:
          app-id: ${{ secrets.APP_ID }}
          app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
          diff-viewer-owner: Himenon
          diff-viewer-repo-name: compare-action-diff-viewer
