name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/initialize
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Restore Next.js cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('**/*.ts', '**/*.tsx', '**/*.md') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}-
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: package.json
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm build
      - name: Set short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Upload build directory
        uses: actions/upload-artifact@v4
        with:
          name: build-pr-${{ steps.vars.outputs.sha_short }}
          path: .next
          if-no-files-found: error
          include-hidden-files: true
  # ここで別ファイルのワークフローを呼び出す
  call-diff:
    needs: build
    uses: ./.github/workflows/_compare-artifact.yml
    permissions:
      pull-requests: write
      contents: read
      actions: read
    with:
      pr_sha: ${{ needs.build.outputs.sha_short }}
      base_ref: ${{ github.base_ref }}
